appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: IqBR7npYKeaYncEPS80dxqz8rf7h2RNEmYiQAq7//tkrOejQiEYEbHkd7hgV5GAh4I3bG+1/MFW28rMRobcn4L2Rh7jLdv6w/fzGTA6mOSIzlSnSGkDTqnYkCI+HQv0rtlxJI8POajpgHzRP0vv5ASAVcblTwSZ1UHK8mIsP+qZW9K1beD56LOXD5v3WEXXnxoqRX+9BrN3bpgb8z8TItCe1cjME9Ve0bWAqvFoKKm/5SeTMIb4HPMeOeKdgjLW+d5wZf2XZWyJx6IJwm5NiNEgXUD0LKq+rA/ZWbSJROWBx34pic2yC8+z0LnAhd1ukMnZK+Um5biGT+AsMSIgYAzLY230My2aUW0pgE1C+r25Jl6Z3kSwfHD5eWq33CF1gXm+u+1GE/zxfkCMoYQ9afY6s1rYMnYKIReh2+Eiji0RYAfg7+JPB4W1iesw5YY8unTT12eSVHvOw+i6sbeduDQ50VzJ6XZya23HNYHzah40alzxPMOXQQ1Vy8OiZ6CxtEAoFdwaixZA+DNoa1UdWdkwS/HxTFEFLDkJuAiwaGBSU4Ml4raOXLEbLcAAQK9jr2/iLu91Sanq9hlsto7HqCh8ttjPa+T1KR8S80xicQei0sOK5EHqiflFYVyg35/BSsFefHQKxFC5ygpzYWMo+g2X6H9MjmFhKNoMQK9AVBxQ=
conda_forge_output_validation: true
