travis:
  secure:
    BINSTAR_TOKEN: fI8FB6EyLwbiPV8KnMshdVGX5CI06NUuHgUvxzkPdogDnUTqWNj5WfTwzPruh+k6w/HpjhX1G4ILKwdonZuvARRK9WgneaVMMueTEqo/x8dOFJXE1/arlpzqhSBQheoheTB/UK/cTlWBmAJ5PKU2/r9+QbWGaZrKtPDKFXED1kqcLcYUQeevmQYZvbQhgwWSPLTik39Soj+5TfLPg1Jh4qIe6/6tyyj40hWrQt/+ZcQzchSqF1a6zxwg9AJzrm+3bQh7Dbs2A74YMJLE0GBAJN8qRbay/CQasLLaLEgjr7wZEryG7Re61fdf7dlzJwBd2SLjui5Dx05jBrlBGRiUjSipKEKkYmwznkPzVmQIlX07KTrgBKhr780567ZtzvcDERxXODARg7aiWgyHP3RfpeuG0oqNEUGf/rtG4ptEeJd2FyigawTuL7Pgh4LvJykCl2jhKo6P4fUtGUrVQU2qPRzOiJdNXHegRGGS+cF1sj6wNt1IT51fY1BLJI5kfngSQj9EpVhZtVZ1Si4imbJoNk6Ep896gXrX96hipgl4ek3GyCuUk1tLdDANZ6k8tJlbdx+rUbi8zGdAVTVG3ScBZ6Cq9og/bFRNlfynzavHxtBakyllAoi9spGPKSpwdZcJc9qCdwozcgTP0wl9+Kt+gsPHJGqdCSA2O9P2F2N0Ffc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
